version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: taskmanagement
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - task-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  usuario-service:
    build: ./usuario-service
    container_name: usuario-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskmanagement
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - task-network
  
  tarefa-service:
    build: ./tarefa-service
    container_name: tarefa-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskmanagement
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      USUARIO_SERVICE_URL: http://usuario-service:8080
    ports:
      - "8082:8080"
    depends_on:
      postgres:
        condition: service_healthy
      usuario-service:
        condition: service_started
    networks:
      - task-network

networks:
  task-network:
    driver: bridge

volumes:
  postgres-data: